# Generated by Django 6.0.2 on 2026-02-10 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='merch/additional/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
            },
        ),
        migrations.CreateModel(
            name='MerchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('clothing', 'Одежда'), ('accessories', 'Аксессуары'), ('vinyl', 'Винил'), ('cd', 'CD'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₽)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (для скидки)')),
                ('image', models.ImageField(upload_to='merch/', verbose_name='Фото товара')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('low_stock', 'Мало на складе'), ('out_of_stock', 'Нет в наличии'), ('pre_order', 'Предзаказ')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый товар')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('additional_images', models.ManyToManyField(blank=True, to='planet_merch.merchimage', verbose_name='Дополнительные фото')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
