# Generated by Django 5.2.11 on 2026-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('venue', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ticket_url', models.URLField(blank=True, verbose_name='Ссылка на билеты')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('past', 'Прошедший'), ('cancelled', 'Отменён')], default='upcoming', max_length=20)),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
                'ordering': ['date'],
            },
        ),
    ]
