# Generated by Django 6.0.2 on 2026-02-11 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_media', '0003_alter_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видео в формате MP4 (рекомендуется)', null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])], verbose_name='Видеофайл (MP4)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
