# Generated by Django 5.2.11 on 2026-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название группы', max_length=200)),
                ('description', models.TextField(verbose_name='Описание группы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('founded_year', models.IntegerField(verbose_name='Год основания')),
            ],
            options={
                'verbose_name': 'Информация о группе',
                'verbose_name_plural': 'Информация о группе',
            },
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100, verbose_name='Инструмент/роль')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('bio', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['order'],
            },
        ),
    ]
